[workflow]
slug = "sentinel-2-cloudfree-mosaic-F8yVcPRfw2AkoZ"
root = "."
runner = "runner:runner"

[build]
include = [
  "pyproject.toml",
  "uv.lock",
  "**/*.py",
]
# Respect .gitignore when selecting files for the release.
use_gitignore = true
