[workflow]
slug = "burn-scar-mapping-EngRbLn7Zb8iSa"
root = "."
runner = "runner:runner"

[build]
include = [
  "pyproject.toml",
  "uv.lock",
  "**/*.py",
]
# Respect .gitignore when selecting files for the release.
use_gitignore = true
