[workflow]
slug = "seasonal-rgb-timelapse-AGimUihHGGahtT"
root = "."
runner = "runner:runner"

[build]
include = [
  "pyproject.toml",
  "uv.lock",
  "**/*.py",
]
# Respect .gitignore when selecting files for the release.
use_gitignore = true
